
service: slsplugindev

provider:
  name: aws
  runtime: dotnetcore3.1
  region: us-west-2

plugins:
  - serverless-api-client-certificate

package:
  individually: true

custom:
  serverlessApiClientCertificate:
    rotateCerts: true
    daysLeft: 30

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip
    events:
      - http:
          path: hello
          method: get

#    Define function environment variables here
    environment:
      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
resources:
  Resources:
    RestApi:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /services/${self:service}-${opt:stage}/apiId
        Type: String
        Value:
          Ref: ApiGatewayRestApi
  Outputs:
    RestApi:
      Value: 
        Ref: ApiGatewayRestApi

        
